### ISSUE TITLE
Load data fix ARRAYS to DICT

### ISSUE THREAD

**Issue by WilliamZimmerman83** [martineastwood/GBQ#13]
@ChaimKesler I noticed that while this data uploads into BQ and looks good - the unfortunate thing is the data is entirely in ARRAY format so none of the rows are actually related (impossible to do joins etc.)

So I worked through a solution to get it working - however I don't think it works with the autodetect schema... so I am hoping for some suggestions the code would go before making the temp table and it converts the dataframe to a series of dictionaries (it also trims numeric variables to the maximum allowed by BQ - however I couldn't get this to work with the --autodetect we had earlier and had to construct the table ahead of time...:

```
function convert_df_to_json_rows(df::DataFrame)
    num_rows = size(df, 1)
    num_columns = size(df, 2)
    
    json_rows = []
    
    for i in 1:num_rows
        dict_row = Dict{Symbol, Any}()
        for j in 1:num_columns
            column_name = Symbol(names(df)[j])
            column_value = df[i, j]
            
            # Check if the column value is numeric
            if eltype(column_value) <: Number
                column_value = round(column_value, digits=9)
            end
            
            dict_row[column_name] = column_value
        end
        json_row = JSON.json(dict_row)
        push!(json_rows, json_row)
    end
    return json_rows
end

dicts_df = convert_df_to_json_rows(df)

# Wrte to temporary JSON file
temp_file = joinpath(pwd(), "temp.json")
open(temp_file, "w") do f
    for dict_row in dicts_df
        println(f, dict_row)
    end
end

```

**Comment by ChaimKesler** [comment]
@WilliamZimmerman83 Just seeing this - that is interesting. I didn't have the array issue when testing locally. I'll try it today and see what happens.

**Comment by WilliamZimmerman83** [comment]
Hey @martineastwood could you grant co-author permissions for ChaimKesler and myself?

Cheers,

**Comment by martineastwood** [comment]
@WilliamZimmerman83 - sure, I've added you both as collaborators.

Thanks,
