### ISSUE TITLE
Failed to precompile GBQ - macOS

### ISSUE THREAD

**Issue by GarrettMooney** [martineastwood/GBQ#5]
Using Julia 1.1.0 on macOS 10.14.5, I am unable to precompile GBQ.
![Screen Shot 2019-10-24 at 2 28 42 PM](https://user-images.githubusercontent.com/4910020/67514420-b11dd780-f66a-11e9-8b4d-0b9139163d0e.png)

**Comment by martineastwood** [comment]
Thanks for the screenshot, probably going to be next week though before I get chance to look into this

**Comment by martineastwood** [comment]
Okay this should be fixed now

![Screen Shot 2019-10-31 at 09 36 48](https://user-images.githubusercontent.com/8270216/67935585-14a38a00-fbc2-11e9-9ec3-14bdf243a77a.png)
